name: Production Release

# Action activates on tag push
on:
  push:
    tags:
      - "v*"

# Setup the Job
jobs:
  Application-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set version environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Print version environment variable
        run: echo ${RELEASE_VERSION} && sh -c "echo ${RELEASE_VERSION}"
      - name: Run make check-version
        run: make