name: Production Release

# Action activates on tag push
on: 
  push:
    tags:
      - "v*"

# Setup the Job
jobs:
  Application-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set version environment variable
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/} | sed -e 's/^v//' 2>&1)" >> $GITHUB_ENV
      - name: Print version environment variable
        run: echo ${RELEASE_VERSION} && sh -c "echo ${RELEASE_VERSION}"
      - name: Run make check-version
        run: make check-version