name: Production Release

# Action activates on tag push
on:
  push:
    tags:
      - "v*"

# Setup the Job
jobs:
  Application-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set version environment variable
        run:
        make get-version
        echo "RELEASE_VERSION=$(make get-version 2>&1)" >> $GITHUB_ENV
      - name: Print version environment variable
        run: echo ${RELEASE_VERSION} && sh -c "echo ${RELEASE_VERSION}"
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Run make check-version
        run: make check-version